# fly.toml (for backend repository)
app = "email-sorting-backend"
primary_region = "dfw"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"
    timeout = "5s"
    headers = {}

# VM configuration
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Metrics endpoint (optional)
[metrics]
  port = 8080
  path = "/metrics"

# Console configuration for debugging
console_command = "/bin/bash"

# Deploy configuration
[deploy]
  strategy = "rolling"
  wait_timeout = "5m"